param(
    [Parameter(Mandatory=$true)][string]$XrayRoot
)

$ErrorActionPreference = "Stop"
$XrayRoot = (Resolve-Path $XrayRoot).Path
$r4 = Join-Path $XrayRoot "src\Layers\xrRenderPC_R4\r4.cpp"
$text = Get-Content $r4 -Raw

function Replace-ExactlyOnce([string]$source, [string]$from, [string]$to, [string]$label)
{
    $needle = $from.Trim()
    $count = ([regex]::Matches($source, [regex]::Escape($needle))).Count
    if ($count -ne 1) { throw "$label expected exactly once, got $count" }
    return $source.Replace($needle, $to.Trim())
}

# Action22 does not replace GAMMA/SSS shader files. R4 patches the source text
# only for dedicated tree-branch alpha-test pixel shaders before source CRC
# calculation and D3DCompile. This preserves the user's installed shader body
# and automatically invalidates stale generated bytecode when the setting or
# strength changes.
$old = @'
static inline bool match_shader_id(LPCSTR const debug_shader_id, LPCSTR const full_shader_id,
                                   FS_FileSet const& file_set, string_path& result);

HRESULT CRender::shader_compile(
'@
$new = @'
static inline bool match_shader_id(LPCSTR const debug_shader_id, LPCSTR const full_shader_id,
                                   FS_FileSet const& file_set, string_path& result);

namespace
{
struct OptiBridgeFloraAlphaState
{
    bool loaded = false;
    bool enabled = false;
    bool logged = false;
    float widthScale = 0.25f;
};

OptiBridgeFloraAlphaState g_optibridgeFloraAlpha;

void OptiBridge_LoadFloraAlphaConfig()
{
    if (g_optibridgeFloraAlpha.loaded)
        return;

    char path[MAX_PATH] = {};
    GetModuleFileNameA(nullptr, path, MAX_PATH);
    char* slashA = strrchr(path, '\\');
    char* slashB = strrchr(path, '/');
    char* slash = slashA > slashB ? slashA : slashB;
    if (slash)
        *(slash + 1) = 0;
    strcat_s(path, "optibridge.ini");

    g_optibridgeFloraAlpha.enabled =
        GetPrivateProfileIntA("OptiBridge", "FloraAlphaStabilization", 0, path) != 0;

    char scaleText[32] = {};
    GetPrivateProfileStringA("OptiBridge", "FloraAlphaWidthScale", "0.25",
        scaleText, sizeof(scaleText), path);
    g_optibridgeFloraAlpha.widthScale = (float)atof(scaleText);
    g_optibridgeFloraAlpha.widthScale =
        _max(0.0f, _min(1.0f, g_optibridgeFloraAlpha.widthScale));
    g_optibridgeFloraAlpha.loaded = true;

    Msg("* [OptiBridge] Action22 flora alpha stabilization %s, derivative width scale %.3f",
        g_optibridgeFloraAlpha.enabled ? "on" : "off",
        g_optibridgeFloraAlpha.widthScale);
}

bool OptiBridge_IsTreeAlphaPixelShader(LPCSTR name, LPCSTR target)
{
    OptiBridge_LoadFloraAlphaConfig();
    if (!g_optibridgeFloraAlpha.enabled || !name || !target || target[0] != 'p')
        return false;

    LPCSTR base = name;
    if (LPCSTR slash = strrchr(name, '\\')) base = slash + 1;
    if (LPCSTR slash = strrchr(base, '/')) base = slash + 1;

    // SSS/GAMMA dedicated foliage alpha-test family. Deliberately do not
    // touch generic deffer_base_aref shaders used by fences/grates/etc.
    return 0 == strncmp(base, "deffer_tree_branch_aref_", 24);
}

void OptiBridge_BuildTreeAlphaSource(
    LPCSTR name,
    DWORD const*& source,
    UINT& sourceLength,
    xr_string& storage)
{
    char prefix[512] = {};
    xr_sprintf(prefix,
        "// OptiBridge Action22 tree alpha stabilization\n"
        "#define OPTIBRIDGE_FLORA_ALPHA_WIDTH_SCALE %.8ff\n"
        "#define clip(x) clip((x) + OPTIBRIDGE_FLORA_ALPHA_WIDTH_SCALE * fwidth(x))\n",
        g_optibridgeFloraAlpha.widthScale);

    storage.assign(prefix);
    storage.append(reinterpret_cast<LPCSTR>(source), sourceLength);
    source = reinterpret_cast<DWORD const*>(storage.data());
    sourceLength = (UINT)storage.size();

    if (!g_optibridgeFloraAlpha.logged)
    {
        Msg("* [OptiBridge] Action22 patching tree alpha shader source: %s", name);
        g_optibridgeFloraAlpha.logged = true;
    }
}
} // namespace

HRESULT CRender::shader_compile(
'@
$text = Replace-ExactlyOnce $text $old $new "Action22 helper insertion seam"

# Dedicated tree alpha shaders must use generated cache entries while Action22
# is active. Otherwise an installed precompiled shader could bypass source
# compilation entirely and therefore bypass our source patch.
$old = @'
	string_path temp_file_name, file_name;
	bool const useGeneratedShaderCache =
		psDeviceFlags2.test(rsPrecompiledShaders) || !match_shader_id(name, sh_name, m_file_set, temp_file_name);
'@
$new = @'
	string_path temp_file_name, file_name;
	const bool optibridgeTreeAlpha = OptiBridge_IsTreeAlphaPixelShader(name, pTarget);
	bool const useGeneratedShaderCache =
		optibridgeTreeAlpha || psDeviceFlags2.test(rsPrecompiledShaders) ||
		!match_shader_id(name, sh_name, m_file_set, temp_file_name);
'@
$text = Replace-ExactlyOnce $text $old $new "Action22 generated-cache policy seam"

# Patch before getShaderSourceCrc32 so the injected strength becomes part of
# the source identity. Changing FloraAlphaWidthScale on the next game launch
# therefore causes a normal CRC mismatch/recompile rather than requiring the
# user to manually clear the shader cache.
$old = @'
	u32 source_crc = 0;
	if (useGeneratedShaderCache)
		source_crc = getShaderSourceCrc32(pSrcData, SrcDataLen, ::Render->getShaderPath());
'@
$new = @'
	xr_string optibridgePatchedSource;
	DWORD const* compileSrcData = pSrcData;
	UINT compileSrcDataLen = SrcDataLen;
	if (optibridgeTreeAlpha)
		OptiBridge_BuildTreeAlphaSource(name, compileSrcData, compileSrcDataLen, optibridgePatchedSource);

	u32 source_crc = 0;
	if (useGeneratedShaderCache)
		source_crc = getShaderSourceCrc32(compileSrcData, compileSrcDataLen, ::Render->getShaderPath());
'@
$text = Replace-ExactlyOnce $text $old $new "Action22 source CRC seam"

$old = @'
			D3DCompile(
				pSrcData,
				SrcDataLen,
'@
$new = @'
			D3DCompile(
				compileSrcData,
				compileSrcDataLen,
'@
$text = Replace-ExactlyOnce $text $old $new "Action22 D3DCompile source seam"

Set-Content $r4 $text -NoNewline
Write-Host "OptiBridge Action22 flora alpha-stability patch applied successfully."
